### ISSUE TITLE
Unable to use properly with multi-monitors

### ISSUE THREAD

**Issue by samjwillis97** [acsandmann/rift#70]
<details>
  <summary>Config here</summary>
  

(these are generated via. Nix say may not look the most efficient)

```toml
[keys]
"Alt + Comma" = "stack_windows"
"Alt + Ctrl + E" = "unjoin_windows"
"Alt + Ctrl + M" = "show_mission_control_all"
"Alt + Ctrl + Q" = "save_and_exit"
"Alt + Ctrl + S" = "serialize"
"Alt + Ctrl + Shift + M" = "show_mission_control_current"
"Alt + F" = "toggle_fullscreen"
"Alt + Shift + D" = "debug"
"Alt + Shift + Equal" = "resize_window_grow"
"Alt + Shift + Minus" = "resize_window_shrink"
"Alt + Shift + Space" = "toggle_window_floating"
"Alt + Slash" = "unstack_windows"
"Alt + Tab" = "switch_to_last_workspace"
"Alt + Z" = "toggle_space_activated"
"comb1 + Ctrl + Space" = "toggle_focus_floating"

[keys."Alt + 1"]
switch_to_workspace = 0

[keys."Alt + 2"]
switch_to_workspace = 1

[keys."Alt + 3"]
switch_to_workspace = 2

[keys."Alt + 4"]
switch_to_workspace = 3

[keys."Alt + 5"]
switch_to_workspace = 4

[keys."Alt + 6"]
switch_to_workspace = 5

[keys."Alt + 7"]
switch_to_workspace = 6

[keys."Alt + 8"]
switch_to_workspace = 7

[keys."Alt + 9"]
switch_to_workspace = 8

[keys."Alt + H"]
move_focus = "left"

[keys."Alt + J"]
move_focus = "down"

[keys."Alt + K"]
move_focus = "up"

[keys."Alt + L"]
move_focus = "right"

[keys."Alt + Shift + Down"]
join_window = "down"

[keys."Alt + Shift + Left"]
join_window = "left"

[keys."Alt + Shift + Right"]
join_window = "right"

[keys."Alt + Shift + Up"]
join_window = "up"

[keys."comb1 + 1"]
move_window_to_workspace = 0

[keys."comb1 + 2"]
move_window_to_workspace = 1

[keys."comb1 + 3"]
move_window_to_workspace = 2

[keys."comb1 + 4"]
move_window_to_workspace = 3

[keys."comb1 + 5"]
move_window_to_workspace = 4

[keys."comb1 + 6"]
move_window_to_workspace = 5

[keys."comb1 + 7"]
move_window_to_workspace = 6

[keys."comb1 + 8"]
move_window_to_workspace = 7

[keys."comb1 + 9"]
move_window_to_workspace = 8

[keys."comb1 + H"]
move_node = "left"

[keys."comb1 + J"]
move_node = "down"

[keys."comb1 + K"]
move_node = "up"

[keys."comb1 + L"]
move_node = "right"

[modifier_combinations]
comb1 = "Alt + Shift"

[settings]
animate = true
animation_duration = 0.35
animation_easing = "ease_in_out_cubic"
animation_fps = 100.0
auto_focus_blacklist = []
default_disable = false
focus_follows_mouse = false
hot_reload = true
mouse_follows_focus = false
mouse_hides_on_focus = true
run_on_start = ["/nix/store/678j7hx2bw2qi72f93iqbsnhbb26l8l1-rift-v0.0.5/bin/rift-cli subscribe cli --event workspace_changed --command sh --args -c --args '/nix/store/sq215c55n6r56nr7i64j48v8zb8hqykh-sketchybar-2.22.1/bin/sketchybar --trigger rift_workspace_changed RIFT_WORKSPACE_NAME=\"$RIFT_WORKSPACE_NAME\" RIFT_WORKSPACE_ID=\"$RIFT_WORKSPACE_ID\"'", "/nix/store/678j7hx2bw2qi72f93iqbsnhbb26l8l1-rift-v0.0.5/bin/rift-cli subscribe cli --event windows_changed --command sh --args -c --args '/nix/store/sq215c55n6r56nr7i64j48v8zb8hqykh-sketchybar-2.22.1/bin/sketchybar --trigger rift_windows_changed RIFT_WORKSPACE_NAME=\"$RIFT_WORKSPACE_NAME\" RIFT_WINDOW_COUNT=\"$RIFT_WINDOW_COUNT\"'"]

[settings.gestures]
distance_pct = 0.12
enabled = false
fingers = 3
haptic_pattern = "level_change"
haptics_enabled = true
invert_horizontal_swipe = false
skip_empty = true
swipe_vertical_tolerance = 0.4

[settings.layout]
mode = "traditional"

[settings.layout.gaps.inner]
horizontal = 0
vertical = 0

[settings.layout.gaps.outer]
bottom = 0
left = 5
right = 5
top = 54

[settings.layout.stack]
stack_offset = 30.0

[settings.ui.menu_bar]
enabled = true
show_empty = true

[settings.ui.mission_control]
enabled = true
fade_duration_ms = 180.0
fade_enabled = true

[settings.ui.stack_line]
enabled = false
horiz_placement = "top"
thickness = 3.0
vert_placement = "left"

[settings.window_snapping]
drag_swap_fraction = 0.3

[virtual_workspaces]
auto_assign_windows = true
default_workspace = 0
enabled = true
preserve_focus_per_workspace = true
workspace_names = ["Workspace 1"]
[[virtual_workspaces.app_rules]]
floating = true
title_substring = "Preferences"
```

</details>

Whenever I am using two monitors my windows will be initially assigned to the monitor the windows are on, in most cases the primary display, though as soon as I try and go to a different workspace all the windows will move to the secondary monitor and are not possible to bring back to the primary display.

It seems like all the workspaces are assigned to the secondary monitor and none to the primary (or something like that?)

The only thing I've really seen discussed around this is the setting `Displays have separate Spaces` which is on.

All of my `rift-cli` queries are currently hanging as well so struggling to debug using that 😕 

## Videos

I start the service with `rift service start` in the terminal and then press `Alt + Shift + 2` to attempt to move one window to the second space and this is the result

### Primary Monitor

https://github.com/user-attachments/assets/a896b395-70c5-4973-bce3-08696b08aa2d

### Secondary Monitor
https://github.com/user-attachments/assets/b70319b1-8c33-442f-8070-291641ffeab9

**Comment by acsandmann** [comment]
yeah i think i need to use monitor uuid instead of spaceid when there are multiple monitors to avoid that from happening (spaces move around when bringing a laptop back from sleep, so the spaceids essentially switxh). are you on the latest version? i made some updates to the underlying mach port but it works fine for me, i wonder if its an issue with nix... 

is there a way to install it via homebrew in nix? 



i dont use nix so unsure about what it entails as there are some weird edge cases with running thru brew(which have been addressed) but i wonder if they are any for nix.

**Comment by samjwillis97** [comment]
I've just added some videos which may help to show it better, I could install via brew for debugging purposes, I'm building from source with nix. Will let you know how it goes

**Comment by samjwillis97** [comment]
Still getting the same experience when installing with `brew`

**Comment by samjwillis97** [comment]
Just remembered there is possibly one oddity with my system, which is one of the monitors (secondary) is through DisplayLink Manager, it does show up normally in the Display settings but something probably worth calling out.

**Comment by acsandmann** [comment]
oh  i think i might have misread this issue. each monitor/space has its *own* set of virtual workspaces as that is a macos restriction. Rift is not possible (due to os restrictions) to move windows between macos spaces. The user must drag them between or drag them within macos' native mission control. I understand this is a divergence from how AeroSpace works but there are so many benefits to having per space isolation so we have to deal with it..

**Comment by samjwillis97** [comment]
Ah okay that makes sense but what should be happening in that video? 
They start in a workspace on the Primary Display I try to move one of the windows to a workspace on that same display with `Alt + Shift + 2` then they both appear on the second display.

**Comment by diocletiann** [comment]
> oh i think i might have misread this issue. each monitor/space has its _own_ set of virtual workspaces as that is a macos restriction. Rift is not possible (due to os restrictions) to move windows between macos spaces. The user must drag them between or drag them within macos' native mission control. I understand this is a divergence from how AeroSpace works but there are so many benefits to having per space isolation so we have to deal with it..

how does Yabai do it?

**Comment by acsandmann** [comment]
@diocletiann yabai can do everything we do through virtual workspaces with native macos spaces because with sip disabled you can move windows between them(in addition to many many other things). 

in aerospace all monitors share one space. i dont like the tradeoffs of that so each macos space in rift has its own isolated set of virtual workspaces.

**Comment by alle-ox** [comment]
@acsandmann need check how Flashspace manage workspaces and displays.
If I remembered correctly, it somehow worked there.

Yep, it use native hide for hiding apps.

**Comment by sytherax** [comment]
I gave this a crack today. 

I was able to get working multi-monitors with features 

* moving window to workspace in different display, 
* switch workspace on other display along with native hide as @alle-ox mentioned without requiring SIP or also while keeping the `Displays have separate Spaces` turned on. 
* Mouse warp when switching to the workspace on other display
* Navigation to other workspace in other display respecting the placement of the display. 

However there are race conditions (possibly preexisting) that still need addressing. 

It appears to work quite nicely. (kind of bastardised code, but would like a set of eyes, might not have time to finish it up)

Looks like the problem with app hiding is that it doesn't seem to work nicely with child windows 😩

**Comment by sytherax** [comment]
It seems that offscreen solution is the only way to go, the problem with this is a nasty race condition bug/animation bug??, that attempts to grab the windows from one display to another, depending on where you offscreen them just when you switch workspace (if they overlay certain portion of the real estate of that window to a different screen, they just move over).

Going to also try an overlay approach, which doesn't move the hidden windows, but creates a fullscreen overlay in front of them.

**Comment by sytherax** [comment]
I have got a [branch](https://github.com/sytherax/rift/tree/syth/multi-monitor-support) (very hacky), where currently I have overlay approach implemented. There is an small issue when switching workspace, if you are some windows  like chrome, that window also appears on the other workspace with the overlay, But the rest should work as I mentioned in https://github.com/acsandmann/rift/issues/70#issuecomment-3475958377

I couldn't get either approaches (offscreen or overlay) to work correctly.

I modified the default toml to assign workspace to each display. To start just use a dual monitor and start like

`cargo run --bin rift -- --config rift.default.toml` 

And use Alt-Z in both displays to active managing the space for both first. Would love to get your thoughts or ideas on it.

Also added a command to get the displays like

`cargo run --bin rift-cli query displays`

And querying workspaces will also show you the display they are currently in.

**Comment by acsandmann** [comment]
interesting i will check it out. must be complicated considering how spaceids are pretty depended on... not opposed to something like that though

**Comment by alle-ox** [comment]
@sytherax @acsandmann I think best solution, mix both method. 
If need switch workspace from one display to another, just use native hide and move it.
HideInCorner needed for PiP workaround, like it working in Flashspace. Because you can't minimize application, without PiP window.
But "HideInCorner" have limitation for display arrangement like described in Aerospace documentation. And need write system for choosing optimal corner for hiding.

**Comment by sytherax** [comment]
> [@sytherax](https://github.com/sytherax) [@acsandmann](https://github.com/acsandmann) I think best solution, mix both method. If need switch workspace from one display to another, just use native hide and move it. HideInCorner needed for PiP workaround, like it working in Flashspace. Because you can't minimize application, without PiP window. But "HideInCorner" have limitation for display arrangement like described in Aerospace documentation. And need write system for choosing optimal corner for hiding.

Tried to hide it correctly for multi-monitor, the offscreen solution is just so tricky to get right. If it detects a portion of the window falls in the another window when offscreen'ed, something is causing to grab the offscreen window and then instead put it on other display. But I am unsure where this is happening. What we want is ideally, for that window to be ignored entirely during animate layout if it is hidden and of workspace/display it doesn't own. 

My second last commit is the one where the offscreen still works, but those hidden window are visible in that display 😅 
I'd rather prefer offscreen solution if we are able to get it to work than the overlay one (this was only added in the last committed, as I got frustrated lol)

**Comment by acsandmann** [comment]
@sytherax do you think it is rift thinkin gthe window is being dragged to the other display or something? or macos itself? kind of unsure as i don't really work with multiple monitors much and if so its max 2.

**Comment by sytherax** [comment]
@acsandmann I got success with this, ie handling hidden windows correctly. It appears there are certain scenarios where windows get destroyed and lost, especially if the hidden window coordinates tend to fall in a different display's bounds, causing us to treat them as new windows and thus the "grabbing" effect when reanimating back onscreen.

I got this mechanism working by tracking windows when we receive `WindowDestroyed` events from macOS and then restoring them to their previous workspace on the display they originally belonged to.

- When hiding windows in inactive workspaces, we position them offscreen (typically at bottom-right corner)
- If these offscreen coordinates happen to overlap with another display's screen bounds, macOS's coordinate-based window ownership detection reassigns the window
- When switching workspaces, the "destroyed" window reappears but gets assigned to the wrong display based on its offscreen coordinates
- This causes the visual "grabbing" effect as windows jump between displays

There are lot of minor issues here and there, but I am confident we can do this feature quite seamlessly. I'll push up my changes soon but next few weeks, won't likely have a second display myself to continue developing.

**Comment by acsandmann** [comment]
okay sounds like this is getting really close to something that's actually feasible. i haven't really looked at the code too closely so i have a few surface level questions...

1. how can we move windows between spaces/displays? iirc there is no sip friendly way to programatically do it that doesn't rely on things like titlebars (which not all windows have).
2. how does native hiding work? if done programmatically is there no animation? 
3. how much complexity does this add? or does it decrease complexity? i can imagine better handling of drags would actually be able to decrease complexity as we have a lot of things listening to/relying on drag state whilst windows are moving.


ps. i think you can simulate having multiple displays on one screen with betterdisplay. someone apparently uses an ultrawide+aerospace by segmenting their ultrawide into 3 "virtual" displays

**Comment by sytherax** [comment]
@acsandmann 

1. Yeah it doesn't require disabling SIP at all as it doesn't use the spaces apis. The windows are set by using coordinates relative to the main display. ie display to the left of main display would have negative coordinates, along with suppression of some of the events. 
2. Same as before, I am not using native hiding, I am not sure if it will be any useful once we iron out the bugs, as you can't hide/unhide individual windows for the same app. The only thing is you have to keep track of window even after they are destroyed, so you know where they should re-appear. This might also be the solution to https://github.com/acsandmann/rift/issues/81 
  In my testing I found, you tend to have less artifacts, when the window is hidden within the same coordinate system as they are displayed in. However sometimes you can't always have the hide corner as the same display. (I need to check if there are any issues in using other than bottom-right corners of the screen, and also unavoidable if you have a 9-screen layout, with 3 on top, middle and bottom. What corners for the middle display 😄 )
  But this might be because we need to modify the window state in several places, I am still understanding the codebase.

3. Other than gracefully handling window events in cases like these and the other fullscreen issue, it will fit quietly naturally. This does add a significant amount of code to make it featureful like awareness about displays arrangement (being able to navigate in the direction of the arrangement) 

I do use an ultrawide setup as the center and my laptop on the left (just laptop now as i am travelling). I tend to use my mouse very less, and don't use the laptop screen at all. This feature could change that 😎  . 

Might try better display when I get the time.

**Comment by acsandmann** [comment]
i don't think this is the solution to #81. that is a result of rely on sls iterators for window bounds when we receive window moved/resized events. part of the refactor of rifts state will make it so we can just call axuielement.frame() and we will have no jitter.

sls iterator window bounds can *sometimes* be out of date so we need to lean to axuielement.frame() its just the axuielement is really "far" away in rift right now. (isolated in its app thread)

**Comment by sytherax** [comment]
Hmm, I am almost certain for fullscreen windows [`handle_window_destroyed‎`](https://github.com/acsandmann/rift/blob/main/src/actor/reactor/events/window.rs#L65) also gets called for that window causing it to forget its previous layout?

**Comment by acsandmann** [comment]
yeah it does but we need to do it that way or handling windows moving between spaces/displays becomes very (impossibly) complicated.

**Comment by sytherax** [comment]
Ok I haven't fully grasped what logic goes into determining that the Window is destroyed, but can't we have transitory states like `WindowFullscreen`, `WindowMovedToDisplay` since it appears the concept of what destroyed means is up to us and now that we can simply move windows to other displays using coordinates relative to main display? 

I was previously under the assumption that WindowDestroyed was directly coming from MacOS Apis

**Comment by acsandmann** [comment]
Well the only issue with that is we listen to certain lower level events because listening to the normal kaxuielementdestroyed (like many other wms) doesn't actually work that well as it doesn't fire sometimes. thus we would end up having ghost windows since we don't want to query the full state that often (we actually almost never do and its one of the main reasons why rift is better than aerospace, since they combat this with full state updates because they don't like private apis). 

and while it would be really nice to distinguish the types of destroyed events it comes with a lot of extra state tracking because there seems to be a lot of "noise" and duplicated events(on macos' side) that mess up this state tracking.



Tldr flow is:
window_notify (low level subscription to the lowest level macos window events) => queries slsiterator to get state in order to create a window destroyed method => reactor => we check if its fullscreen/user space and what we know about the window => we send a windowdestroyed to the layout => layout removes window

**Comment by acsandmann** [comment]
@sytherax this may he interesting for proper multi monitor support: https://github.com/mogenson/WarpMouse.spoon

**Comment by brianwk** [comment]
In HammerSpoon I do the following to move some windows to my external display automatically. It isn't as good as Aerospace but it prevents me from having to do it manually which I hate.

*Edit:* Updated this function so that it doesn't move a window to a screen it's already on...

```lua
codeFilter = hs.window.filter.new{'Code - Insiders', 'Code'}

function windowCreatedCallback(window, appName, event)
    local targetScreen = hs.screen.find(WORK_DISPLAY_UUID)
    local windowScreen = window:screen()
    if targetScreen and targetScreen:getUUID() ~= windowScreen:getUUID() then
        window:moveToScreen(targetScreen, false, false, 0)
        if appName == "WezTerm" then
            wmMoveToWorkspace(window, "9")
        end
    end
end

codeFilter:subscribe(hs.window.filter.windowCreated, windowCreatedCallback)
```

**Comment by acsandmann** [comment]
window spaz is fixed on main
